#include "p3_functions_decl.hpp"

// If a GPU build, without relocatable device code enabled, make all code available
// to the translation unit; otherwise, ETI is used.
#if defined(EAMXX_ENABLE_GPU) && !defined(KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE) \
                                && !defined(KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE)
# include "p3_table3_impl.hpp"
# include "p3_table_ice_impl.hpp"
# include "p3_back_to_cell_average_impl.hpp"
# include "p3_dsd2_impl.hpp"
# include "p3_upwind_impl.hpp"
# include "p3_find_impl.hpp"
# include "p3_conservation_impl.hpp"
# include "p3_autoconversion_impl.hpp"
# include "p3_rain_self_collection_impl.hpp"
# include "p3_impose_max_total_ni_impl.hpp"
# include "p3_calc_rime_density_impl.hpp"
# include "p3_cldliq_imm_freezing_impl.hpp"
# include "p3_droplet_self_coll_impl.hpp"
# include "p3_cloud_sed_impl.hpp"
# include "p3_cloud_rain_acc_impl.hpp"
# include "p3_ice_sed_impl.hpp"
# include "p3_rain_sed_impl.hpp"
# include "p3_rain_imm_freezing_impl.hpp"
# include "p3_get_time_space_phys_variables_impl.hpp"
# include "p3_evaporate_rain_impl.hpp"
# include "p3_update_prognostics_impl.hpp"
# include "p3_ice_collection_impl.hpp"
# include "p3_ice_deposition_sublimation_impl.hpp"
# include "p3_ice_relaxation_timescale_impl.hpp"
# include "p3_ice_nucleation_impl.hpp"
# include "p3_ice_melting_impl.hpp"
# include "p3_calc_liq_relaxation_timescale_impl.hpp"
# include "p3_ice_cldliq_wet_growth_impl.hpp"
# include "p3_get_latent_heat_impl.hpp"
# include "p3_check_values_impl.hpp"
# include "p3_incloud_mixingratios_impl.hpp"
# include "p3_subgrid_variance_scaling_impl.hpp"
# include "p3_main_impl.hpp"
# include "p3_main_impl_part1.hpp"
# include "p3_main_impl_part2.hpp"
# include "p3_main_impl_part3.hpp"
# include "p3_ice_supersat_conservation_impl.hpp"
# include "p3_nc_conservation_impl.hpp"
# include "p3_nr_conservation_impl.hpp"
# include "p3_ni_conservation_impl.hpp"
# include "p3_prevent_liq_supersaturation_impl.hpp"
#endif // GPU || !KOKKOS_ENABLE_*_RELOCATABLE_DEVICE_CODE
