if (compile_threaded)
  string(APPEND CFLAGS " -h omp")
  string(APPEND FFLAGS " -h omp")
  string(APPEND CXXFLAGS " -h omp")
  string(APPEND LDFLAGS " -h omp")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRCRAY")
string(APPEND FC_AUTO_R8 " -s real64")
#string(APPEND FFLAGS " -f free -N 255 -h byteswapio -em")
string(APPEND FFLAGS " -f free -N 255 -em")
if (NOT compile_threaded)
  string(APPEND FFLAGS " -M1077")
endif()
if (DEBUG)
  #cce15 has trouble with -g (C++ only, but removing all for now)
  string(APPEND FFLAGS "  -O0")
  string(APPEND CFLAGS "  -O0")
  string(APPEND CXXFLAGS " -O0")
endif()
set(HAS_F2008_CONTIGUOUS "TRUE")
#string(APPEND LDFLAGS " -Wl,--allow-multiple-definition -h byteswapio")
#string(APPEND LDFLAGS " -Wl,--allow-multiple-definition -Wl,--allow-shlib-undefined")
string(APPEND LDFLAGS " -Wl,--allow-multiple-definition")
set(SUPPORTS_CXX "TRUE")
set(CXX_LINKER "FORTRAN")
