site_name: The C++ E3SM Atmosphere Model (EAMxx)

nav:
  - 'Home': 'index.md'
  - 'User Guide':
    - 'Overview': 'user/index.md'
    - 'Installation': 'common/installation.md'
    - 'Model output': 'user/model_output.md'
    - 'Model input': 'user/model_input.md'
  - 'Developer Guide':
    - 'Overview': 'dev/index.md'
    - 'Installation': 'common/installation.md'
    - 'Style Guide': 'dev/style_guide.md'
    - 'Kokkos and EKAT': 'dev/kokkos_ekat.md'
    - 'Important Data Structures':
      - 'Fields': 'dev/field.md'
      - 'Grids and Remappers': 'dev/grid.md'
      - 'Atmosphere Processes': 'dev/processes.md'
      - 'Managers': 'dev/managers.md'
    - 'I/O': 'dev/io.md'
    - 'Testing':
      - 'Standalone': 'dev/standalone_testing.md'
      - 'Full model': 'dev/cime_testing.md'
      - 'CI and Nightly Testing': 'dev/ci_nightly.md'

edit_uri: ""

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  features:
    - navigation.indices
    - navigation.instant
    - navigation.sections
    - navigation.top
#    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/E3SM-Project/scream
