#include "shoc_functions_decl.hpp"

// If a GPU build, without relocatable device code enabled, make all code available
// to the translation unit; otherwise, ETI is used.
#if defined(EAMXX_ENABLE_GPU) && !defined(KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE)  \
                                && !defined(KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE)  

# include "shoc_calc_shoc_varorcovar_impl.hpp"
# include "shoc_calc_shoc_vertflux_impl.hpp"
# include "shoc_diag_second_moments_srf_impl.hpp"
# include "shoc_diag_second_moments_ubycond_impl.hpp"
# include "shoc_update_host_dse_impl.hpp"
# include "shoc_compute_diag_third_shoc_moment_impl.hpp"
# include "shoc_pblintd_init_pot_impl.hpp"
# include "shoc_compute_shoc_mix_shoc_length_impl.hpp"
# include "shoc_check_tke_impl.hpp"
# include "shoc_linear_interp_impl.hpp"
# include "shoc_clipping_diag_third_shoc_moments_impl.hpp"
# include "shoc_energy_integrals_impl.hpp"
# include "shoc_diag_second_moments_lbycond_impl.hpp"
# include "shoc_diag_second_moments_impl.hpp"
# include "shoc_diag_second_shoc_moments_impl.hpp"
# include "shoc_compute_shr_prod_impl.hpp"
# include "shoc_compute_brunt_shoc_length_impl.hpp"
# include "shoc_compute_l_inf_shoc_length_impl.hpp"
# include "shoc_check_length_scale_shoc_length_impl.hpp"
# include "shoc_diag_obklen_impl.hpp"
# include "shoc_pblintd_cldcheck_impl.hpp"
# include "shoc_length_impl.hpp"
# include "shoc_energy_fixer_impl.hpp"
# include "shoc_compute_shoc_vapor_impl.hpp"
# include "shoc_update_prognostics_implicit_impl.hpp"
# include "shoc_diag_third_shoc_moments_impl.hpp"
# include "shoc_assumed_pdf_impl.hpp"
# include "shoc_adv_sgs_tke_impl.hpp"
# include "shoc_compute_tmpi_impl.hpp"
# include "shoc_integ_column_stability_impl.hpp"
# include "shoc_isotropic_ts_impl.hpp"
# include "shoc_dp_inverse_impl.hpp"
# include "shoc_main_impl.hpp"
# include "shoc_pblintd_height_impl.hpp"
# include "shoc_tridiag_solver_impl.hpp"
# include "shoc_pblintd_surf_temp_impl.hpp"
# include "shoc_pblintd_check_pblh_impl.hpp"
# include "shoc_pblintd_impl.hpp"
# include "shoc_grid_impl.hpp"
# include "shoc_eddy_diffusivities_impl.hpp"
# include "shoc_tke_impl.hpp"
#endif // GPU || !KOKKOS_ENABLE_*_RELOCATABLE_DEVICE_CODE
