include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)
common_setup()

#message(STATUS "pm-gpu PROJECT_NAME=${PROJECT_NAME} USE_CUDA=${USE_CUDA} KOKKOS_ENABLE_CUDA=${KOKKOS_ENABLE_CUDA}")
if ("${PROJECT_NAME}" STREQUAL "E3SM")
  if (USE_CUDA)
    include (${EKAT_MACH_FILES_PATH}/kokkos/nvidia-a100.cmake)
    include (${EKAT_MACH_FILES_PATH}/kokkos/cuda.cmake)
  else()
    include (${EKAT_MACH_FILES_PATH}/kokkos/amd-zen3.cmake)
    include (${EKAT_MACH_FILES_PATH}/kokkos/openmp.cmake)
    #include (${EKAT_MACH_FILES_PATH}/kokkos/serial.cmake)
  endif()
else()
  include (${EKAT_MACH_FILES_PATH}/kokkos/nvidia-a100.cmake)
  include (${EKAT_MACH_FILES_PATH}/kokkos/cuda.cmake)
endif()

include (${EKAT_MACH_FILES_PATH}/mpi/srun.cmake)

set(PYBIND11_PYTHON_VERSION 3.8 CACHE STRING "")
set(Python_EXECUTABLE /pscratch/sd/a/andrep/conda_venvs/fv3net-local/bin/python CACHE STRING "" FORCE)
set(PYTHON_EXECUTABLE /pscratch/sd/a/andrep/conda_venvs/fv3net-local/bin/python CACHE STRING "" FORCE)
set(Python_INCLUDE_DIRS /pscratch/sd/a/andrep/conda_venvs/fv3net-local/include/python3.9 CACHE STRING "" FORCE)
option (SCREAM_ENABLE_ML_CORRECTION "Whether to enable ML correction parametrization" ON)
set(EKAT_MPI_EXTRA_ARGS "${EKAT_MPI_EXTRA_ARGS} --gpus-per-task=1" CACHE STRING "" FORCE)

#option(Kokkos_ARCH_AMPERE80 "" ON)
set(CMAKE_CXX_FLAGS "-DTHRUST_IGNORE_CUB_VERSION_CHECK" CACHE STRING "" FORCE)

#message(STATUS "pm-gpu CMAKE_CXX_COMPILER_ID=${CMAKE_CXX_COMPILER_ID} CMAKE_Fortran_COMPILER_VERSION=${CMAKE_Fortran_COMPILER_VERSION}")
if ("${PROJECT_NAME}" STREQUAL "E3SM")
  if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    if (CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL 10)
      set(CMAKE_Fortran_FLAGS "-fallow-argument-mismatch"  CACHE STRING "" FORCE) # only works with gnu v10 and above
    endif()
  endif()
else()
  set(CMAKE_Fortran_FLAGS "-fallow-argument-mismatch"  CACHE STRING "" FORCE) # only works with gnu v10 and above
endif()
