# This workflow aims to automatically rebuild eamxx documentation
# every time the master branch is updated on github
name: Build and deploy gh-pages branch with Mkdocs

on:
  # Runs every time master branch is updated
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  Build-and-Deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: e3sm-project/scream
          ref: master
          fetch-depth: 0 # Needed, or else gh-pages won't be fetched, and push rejected
          submodules: recursive
      - name: Show action trigger
        run: echo "= The job was automatically triggered by a ${{github.event_name}} event."
      - name: Install python deps
        run: python3 -m pip install mkdocs pymdown-extensions mkdocs-material
      - name: Generate eamxx params docs
        run: ./eamxx-params-docs-autogen
        working-directory: components/eamxx/scripts
      - name: Build and deploy
        working-directory: components/eamxx
        run: mkdocs build && mkdocs gh-deploy
